// <auto-generated />
namespace Bookazon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BookazonV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookazonV3));
        
        string IMigrationMetadata.Id
        {
            get { return "202106151414146_BookazonV3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
